language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lukasve/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukasve/docker-react npm run test